// The solid Font Awesome glyphs the desktop app uses (docs/desktop-audit.md §3),
// re-exported from one place so feature code never imports from
// @fortawesome/free-solid-svg-icons directly and the tree-shaking stays predictable.
//
// Font Awesome Free icons are CC BY 4.0; see docs/design-system.md for the
// attribution that Settings surfaces at M11.

export {
  faArrowLeft,
  faBan,
  faBars,
  faBold,
  faBook,
  faBoxArchive,
  faBoxOpen,
  faChevronDown,
  faChevronUp,
  faCircleInfo,
  faCircleQuestion,
  faCode,
  faEnvelope,
  faEye,
  faFileExport,
  faFileLines,
  faFolderOpen,
  faGear,
  faItalic,
  faLink,
  faListCheck,
  faListOl,
  faListUl,
  faMagnifyingGlass,
  faMoon,
  faPalette,
  faPen,
  faPlus,
  faQuoteRight,
  faSnowflake,
  faSun,
  faTableCells,
  faTag,
  faThumbtack,
  faTrashArrowUp,
  faTrashCan,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
